# Generated by Django 6.0.5 on 2026-05-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDependencies',
            fields=[
                ('dependency_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(blank=True, max_length=50, null=True)),
                ('criticality_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'asset_dependencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_population', models.IntegerField()),
                ('elderly_count', models.IntegerField(blank=True, null=True)),
                ('mobility_impaired_count', models.IntegerField(blank=True, null=True)),
                ('record_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterAffectedZones',
            fields=[
                ('affected_id', models.AutoField(primary_key=True, serialize=False)),
                ('impact_start_time', models.DateTimeField(blank=True, null=True)),
                ('evacuation_status', models.CharField(blank=True, max_length=20, null=True)),
                ('current_water_level_cm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disaster_affected_zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('severity_level', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'disaster_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisasterImpactLog',
            fields=[
                ('impact_id', models.AutoField(primary_key=True, serialize=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recovery_priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disaster_impact_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvacuationPlans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_route_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assembly_point_name', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_evacuation_time_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'evacuation_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfrastructureAssets',
            fields=[
                ('asset_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(blank=True, max_length=50, null=True)),
                ('current_capacity', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_requirement_liters_per_day', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infrastructure_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceConsumptionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('consumed_amount', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource_consumption_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('resource_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('measurement_unit', models.CharField(max_length=20)),
                ('current_level', models.FloatField()),
                ('max_capacity', models.FloatField()),
                ('critical_threshold', models.FloatField()),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('zone_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('population_count', models.IntegerField(blank=True, null=True)),
                ('risk_classification', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'zones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
